### ISSUE TITLE
How many GPUs you use for training on Webface4M

### ISSUE THREAD

**Issue by BossunWang** [mk-minchul/AdaFace#1]
Hi experts, 
I would like to know what device for training as your code used when class number over 20k.
[class_num](https://github.com/mk-minchul/AdaFace/blob/79af07a1ea17cc2022af3ee04fd58485d8ee1187/train_val.py#L27)

**Comment by mk-minchul** [comment]
I used two A100 GPUs with 40GB memory each.

**Comment by BossunWang** [comment]
Thanks for reply.
Nice work and great accuracy achieved 97.66 on IJBC(1e-4).
And spent a lot less on the GPU than I was expected.
