### ISSUE TITLE
 the 18th formula  with AdaFace function that are inconsistent

### ISSUE THREAD

**Issue by eeric** [mk-minchul/AdaFace#10]
the 18th formula in paper is inconsistent with AdaFace code

**Comment by mk-minchul** [comment]
Dear eeric. 
Thanks for pointing out. The scaling term s in equation 18 should be multiplied after all the margin is applied, so it is missing a paranthesis. 
i.e: s(cos(theta_j+g_angle)- g_add)
The code is implemented as intended.

**Comment by eeric** [comment]
yes, good.
