### ISSUE TITLE
Unexpected result when trained resnet50 on MS1MV3 dataset

### ISSUE THREAD

**Issue by jinkun-hao** [mk-minchul/AdaFace#11]
Hi，
I trained resnet50 on MS1MV3 dataset and used the same params as given, but got 0.8882 test_acc on test dataset.

Detailed result:
{'agedb_30_num_test_samples': 12000.0,
 'agedb_30_test_acc': 0.8686666488647461,
 'agedb_30_test_best_threshold': 1.7070000171661377,
 'cfp_fp_num_test_samples': 14000.0,
 'cfp_fp_test_acc': 0.8317142724990845,
 'cfp_fp_test_best_threshold': 1.7899999618530273,
 'lfw_num_test_samples': 12000.0,
 'lfw_test_acc': 0.9645000100135803,
 'lfw_test_best_threshold': 1.5600000619888306,
 'test_acc': 0.8882936239242554}

params:
    --arch ir_50 \
    --use_16bit \
    --batch_size 256 \
    --num_workers 8 \
    --epochs 50 \
    --lr_milestones 12,20,24 \
    --lr 0.1 \
    --head adaface \
    --m 0.4 \
    --h 0.333 \
    --low_res_augmentation_prob 0.2 \
    --crop_augmentation_prob 0.2 \
    --photometric_augmentation_prob 0.2

**Comment by mk-minchul** [comment]
Hi jinkun-hao, When I tested the above configuration by training for few epochs, I get up  the val_acc to be 0.9644. I think there could be a discrepancy either in the env setting or the dataset.
