### ISSUE TITLE
ValueError("Attempting to unscale FP16 gradients.")

### ISSUE THREAD

**Issue by ayush0x00** [mk-minchul/AdaFace#127]
I was trying to train AdaFace on a custom dataset with 10k classes. When the model started to train, I got a ValueError(Attempting to unscale FP16 gradients). It's obvious that FP16 gradients can't be scaled and unscaling/scaling is handled internally by AMP but I am not able to find the root cause of the error. I have also attached a screenshot of the same.

<img width="1440" alt="Screenshot 2023-09-24 at 6 19 33 PM" src="https://github.com/mk-minchul/AdaFace/assets/44584229/7394962e-57a8-4369-9acc-a26ab4b0e4f5">

**Comment by ayush0x00** [comment]
Got resolved. Closing the issue.

**Comment by afm215** [comment]
Can you please explain what was happening to help people who may meet this issue in the future?

**Comment by ayush0x00** [comment]
I accidentally modified the original code PReLU layer to use a torch.Float16 datatype which was causing the issue. The original code didn't have any issues.
