### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by eeric** [mk-minchul/AdaFace#14]
be used to distributed training:    
theta_m = torch.clip(theta + m_arc, min=self.eps, max=math.pi-self.eps)
    return forward_call(*input, **kwargs)
RuntimeError: CUDA error: device-side assert triggered

**Comment by mk-minchul** [comment]
Usually device side assert gets triggered when there is a problem in your input data. You can debug if your input is fed correctly.

**Comment by eeric** [comment]
yes,  because there was a error of computation to dimension of m_arc.
