### ISSUE TITLE
How to use pretrained model to finetune?

### ISSUE THREAD

**Issue by divided7** [mk-minchul/AdaFace#144]
in main.py
`trainer = pl.Trainer(resume_from_checkpoint=resume_from_checkpoint, ...)`
When I use the pretrained weights: **adaface_ir50_casia.ckpt** , I meet some problems:
```
head.kernel: copying a param with shape torch.Size([512, 10572]) from checkpoint, 
the shape in current model is torch.Size([512, 600]).
```
I also try to set the **cls_num=10572**, but:
```
batch_loop.optimizer_loop.optim_progress.optimizer.step.total.completed = self._loaded_checkpoint[
KeyError: 'global_step'
```
How to load weights in torchlight?

**Comment by divided7** [comment]
I try to check the pretrained weights dict:
'adaface_ir50_casia.ckpt'.keys():
 ` ['state_dict']`
our_trained_result 'xxxx.ckpt'.keys():
` ['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'loops', 'callbacks', 'optimizer_states', 'lr_schedulers', 'NativeMixedPrecisionPlugin', 'hparams_name', 'hyper_parameters']`
I will try to replace 'xxxx.ckpt.['state_dict]' with 'adaface_ir50_casia.ckpt.['state_dict]'

**Comment by divided7** [comment]
OK, I solve this problem! Although it's a bit of a cheat.

'''
import torch
import shutil
import os
import argparse


def opt():
    parser = argparse.ArgumentParser()
    parser.add_argument("--embedding_size", type=int, default=512, help='default=512, backbone output dim, no changes generally')
    parser.add_argument("--classnum", type=int, default=600, help='default=600, you should change this parameter!!!')
    parser.add_argument("--pretrained_model_dir", type=str, default="pretrained/adaface_ir50_casia.ckpt", help='default=pretrained/adaface_ir50_casia.ckpt, the pretrained model')
    parser.add_argument("--last_model_dir", type=str, default="experiments/ir50_ms1mv2_adaface_01-29_0", help='default=experiments/ir50_ms1mv2_adaface_01-29_0, the experiment dir, you should modify!')
    return parser.parse_args()


opt = opt()

embedding_size = opt.embedding_size
classnum = opt.classnum
pretrained_model_dir = opt.pretrained_model_dir
last_model_dir = opt.last_model_dir
ckpt_list = []
for f in os.listdir(last_model_dir):
    if f[-5:] == '.ckpt':
        print(f)
        ckpt_list.append(last_model_dir + '/' + f)

ckpt = torch.load(pretrained_model_dir)
for last_model_dir in ckpt_list:
    ckpt1 = torch.load(last_model_dir)

    ckpt_state_dict = ckpt['state_dict']
    print("ckpt_state_dict['head.kernel'].shape[1]", ckpt_state_dict['head.kernel'].shape[1])
    if ckpt_state_dict['head.kernel'].shape[1] != classnum:
        # 如果预训练模型的head kernel输出类别与新项目不匹配
        # initial head.kernel
        head_kernel = torch.zeros((embedding_size, classnum))
        head_kernel.data.uniform_(-1, 1)
        head_kernel.renorm_(2, 1, 1e-5).mul_(1e5)

        # instead initial head.kernel
        ckpt_state_dict['head.kernel'] = head_kernel

    # insert adaface_ir50_casia state dict into  last.ckpt
    ckpt1['state_dict'] = ckpt_state_dict

    # save new_last.ckpt
    torch.save(ckpt1, last_model_dir)
print('预训练模型路径: {}'.format(pretrained_model_dir))
print('替换模型路径: {}'.format(last_model_dir))
'''

**Comment by divided7** [comment]
torchlight真的好难用555

**Comment by divided7** [comment]
By the way, I found the resume checkpoint is not the 'last.ckpt', but 'epoch=xx-step=xx.ckpt'! So I try to modify both .ckpt's state_dict

**Comment by giangnv125** [comment]
> OK, I solve this problem! Although it's a bit of a cheat. The ida is above: replace the state dict.
> 
> first: 'python main.py --custom_num_class 600 --epoch 1 --other ...' #epoch should be 1! and you can get the result dir 'last_model_dir' in 'experiments/...'
> 
> second, use below scrpit:
> 
> ```
> import torch
> import shutil
> import os
> import argparse
> 
> def opt():
>     parser = argparse.ArgumentParser()
>     parser.add_argument("--embedding_size", type=int, default=512, help='default=512, backbone output dim, no changes generally')
>     parser.add_argument("--classnum", type=int, default=600, help='default=600, you should change this parameter!!!')
>     parser.add_argument("--pretrained_model_dir", type=str, default="pretrained/adaface_ir50_casia.ckpt", help='default=pretrained/adaface_ir50_casia.ckpt, the pretrained model')
>     parser.add_argument("--last_model_dir", type=str, default="experiments/ir50_ms1mv2_adaface_01-29_0", help='default=experiments/ir50_ms1mv2_adaface_01-29_0, the experiment dir, you should modify!')
>     return parser.parse_args()
> 
> opt = opt()
> 
> embedding_size = opt.embedding_size
> classnum = opt.classnum
> pretrained_model_dir = opt.pretrained_model_dir
> last_model_dir = opt.last_model_dir
> ckpt_list = []
> for f in os.listdir(last_model_dir):
>     if f[-5:] == '.ckpt':
>         print(f)
>         ckpt_list.append(last_model_dir + '/' + f)
> 
> ckpt = torch.load(pretrained_model_dir)
> for last_model_dir in ckpt_list:
>     ckpt1 = torch.load(last_model_dir)
>     ckpt_state_dict = ckpt['state_dict']
>     print("ckpt_state_dict['head.kernel'].shape[1]", ckpt_state_dict['head.kernel'].shape[1])
>     if ckpt_state_dict['head.kernel'].shape[1] != classnum:
>         # 如果预训练模型的head kernel输出类别与新项目不匹配
>         # initial head.kernel
>         head_kernel = torch.zeros((embedding_size, classnum))
>         head_kernel.data.uniform_(-1, 1)
>         head_kernel.renorm_(2, 1, 1e-5).mul_(1e5)
>         # instead initial head.kernel
>         ckpt_state_dict['head.kernel'] = head_kernel
> 
>     # insert adaface_ir50_casia state dict into  last.ckpt
>     ckpt1['state_dict'] = ckpt_state_dict
> 
>     # save new_last.ckpt
>     torch.save(ckpt1, last_model_dir)
> print('预训练模型路径: {}'.format(pretrained_model_dir))
> print('替换模型路径: {}'.format(last_model_dir))
> ```
> 
> finally: 'python main.py --custom_num_class 600 --epoch 100 --other ...'

Hello,
I try to follow your guide (there are 3 steps, aren't there?) but I don't understand how you do it.  Can you explain more clearly why you use this method?
When you run the python main.py (step 1 and step 3), there is a --other options section. What do _--other_ options include? Do they include _--resume_from_checkpoint_ or _--start_from_model_statedict_?
