### ISSUE TITLE
Some photos are opened upside down, EXIF orientation haven't read

### ISSUE THREAD

**Issue by komoreb11** [mk-minchul/AdaFace#163]
I noticed a problem when using the library. Some photos come out upside down because PIL by default does not read EXIF orientation data. This affects the alignment and subsequently the resulting embeddings. To fix it, it is enough to add

image = ImageOps.exif_transpose(image) after Image.open(“image.jpg”)

**Comment by mk-minchul** [comment]
Thanks for letting the community know.
