### ISSUE TITLE
MODEL PERFORMANCE 

### ISSUE THREAD

**Issue by deeplearningx** [mk-minchul/AdaFace#17]
I reviewed your work. The results look impressive. However, in my tests, I noticed that the performance of arcface is better. Yes, adaface is ahead in benchmarks. But archface provides better recognition in large datasets. Could it be something I did wrong? Or a recommendation?

**Comment by mk-minchul** [comment]
Hi deeplearningx.
There is too little context for me to guess what the problem might be.

**Comment by deeplearningx** [comment]
When I compare img1 and img2 from test images; adaface:0.73, arcface:0.60 gives euclidean distance values. I've had similar results with other data. In general, I obtained values below the results I obtained with arcface.

**Comment by mk-minchul** [comment]
The cosine similarity of the test images may not mean much when the values are compared across different models as the calibration of each model may be different. In your case , try comparing performance with respect to a dataset or the match rankings with a given gallery.

**Comment by deeplearningx** [comment]
You may be right. However, using distance to match encodings in a quality manner is more consistent than using similarity.
As you said, there are of course different calibrations. In my analysis, arcface gives better quality results in both cases. I wonder which arcface code you are referencing. Or can you share your comparison in detail? Is there something you did that I didn't do?

**Comment by deeplearningx** [comment]
It didn't work for me, but thank you for your interest, good luck with your work :)

**Comment by mk-minchul** [comment]
Thanks.
