### ISSUE TITLE
about option "train_data_subset"

### ISSUE THREAD

**Issue by liamsun2019** [mk-minchul/AdaFace#21]
Hi author，
Based on the code, the class num is set to 70722 in case of train_data_subset being set to True. Just wondering how "70722" comes. In addition, what's the target of using subset of emore faces? Just to save the training time? Appreicate your suggestions. Thanks.

**Comment by mk-minchul** [comment]
Hi liamsun2019. 
1. 70722 is specific to the dataset you train on. It is the number of identities in the dataset. 
2. Right. We subset the dataset to train the model faster.

**Comment by liamsun2019** [comment]
Got it, it's clear to me. I tried to train the model using default config options(--arch=ir_18) and the resulted model size is over 200M after extracting the "state_dict" part. I noticed that the provided pretrained model is only 110MB. Curious about the big difference. resnet18 model is supposed not to be so huge.

**Comment by mk-minchul** [comment]
I am not sure what would be the exact cause of the saved file's size. It may be attributed to how the saved checkpoint is from the pytorch-lightning's save checkpoint is written and how it handles the compression.
