### ISSUE TITLE
Question about Figure 3

### ISSUE THREAD

**Issue by HHHedo** [mk-minchul/AdaFace#23]
Hi Minchul Kim，
Thank you for your great work!
I am impressed with Figure 3 in your paper, which is really an excellent illustration. 
I wonder how to draw such figures, and would you please release the tool or code to draw them.

**Comment by mk-minchul** [comment]
Hi HHHedo. 
I used the combination of manim (https://github.com/3b1b/manim) and matplotlib to create the plot. 
The code for creating the figure will not be released. But you may refer to https://www.desmos.com/calculator/6hkxydcrqj for some interactive gst term visualizations. Hope this helps.
