### ISSUE TITLE
Adaface was not good at masked face recogniton

### ISSUE THREAD

**Issue by eeric** [mk-minchul/AdaFace#26]
I was appreciated your good job, it was a pity that Adaface loss was not fit to masked face recogniton.

**Comment by SongJ123** [comment]
I'm generating masked face from the dataset faces_emore, going to train it then.  Wondering you said Adaface loss not fit because the recognition accuray was low or the training process was not going well (like it didn't converge)?

**Comment by eeric** [comment]
I estimate masked face affected Image Quality Indicator, the loss

**Comment by SongJ123** [comment]
> I estimate masked face affected Image Quality Indicator. the recognition accuray was lower.

So you just used the model for face recognition or you trained another model using masked faces? It's not surprising you got a low accuracy if you used a face recognition model for a masked face recognition task.

**Comment by eeric** [comment]
yes.
