### ISSUE TITLE
Train the model using my own dataset

### ISSUE THREAD

**Issue by SongJ123** [mk-minchul/AdaFace#29]
Hi, thank you for your excellent work!
Can you give us a Readme about how to train an adaface model using our own dataset? The training part in this Readme is way too simple, it would be very nice if you can show more examples and data preparations on training :)

**Comment by mk-minchul** [comment]
I am currently working on refactoring. Hope the refactored version will be easier to use.
In the meanwhile, roughly speaking, the steps for using own dataset is 
1. preparing images in folder structure
2. modifying the number of classes to equal to that of the new dataset. 
3. specify the root in the option. 
Hope this helps.
