### ISSUE TITLE
About hyper-parameters of reproduction.

### ISSUE THREAD

**Issue by MouxiaoHuang** [mk-minchul/AdaFace#30]
Hi~ It's a wonderful and excellent work and I'm interested in it. 
But I got some problems when reproducing it, I cannot achieve high-enough accuracy on this task: AdaFace / ResNet100 / MS1MV2. Could you please provide its bash file, just like run.sh or hparams.yaml. 
Looking forward to your reply! Thanks a lot!

**Comment by mk-minchul** [comment]
Hi MouxiaoHuang. Here is the setting I used in with 2 A100 GPUs.

```
python main.py \
    --data_root /mnt/home/kimminc2/data \
    --train_data_path faces_emore \
    --val_data_path ms1m_val/faces_emore \
    --prefix ir101_ms1mv2_adaface \
    --gpus 2 \
    --use_16bit \
    --arch ir_101 \
    --batch_size 512 \
    --num_workers 16 \
    --epochs 26 \
    --lr_milestones 12,20,24 \
    --lr 0.1 \
    --head adaface \
    --m 0.4 \
    --h 0.333 \
    --low_res_augmentation_prob 0.2 \
    --crop_augmentation_prob 0.2 \
    --photometric_augmentation_prob 0.2
```

**Comment by MouxiaoHuang** [comment]
Thanks for your reply! It helps a lot~
