### ISSUE TITLE
Is there a simple example on how to use it?

### ISSUE THREAD

**Issue by martinenkoEduard** [mk-minchul/AdaFace#33]
Is there a simple example on how to use it?

**Comment by mk-minchul** [comment]
As for inference using pre-trained model, I have updated the general inference guideline in REAME. You may check it out if this helps. 
As for training, if you tell me which part of the provided guideline is unclear, I may be able to help.

**Comment by leenaltwayan** [comment]
@mk-minchul Hello, do you have the code on how to run the inference on video instead of images?

Thank you

**Comment by martinenkoEduard** [comment]
> As for inference using pre-trained model, I have updated the general inference guideline in REAME. You may check it out if this helps. As for training, if you tell me which part of the provided guideline is unclear, I may be able to help.

Also how do I prepare my dataset? is it possible just to use image files?
