### ISSUE TITLE
有转onnx的代码吗？

### ISSUE THREAD

**Issue by xingjunhong** [mk-minchul/AdaFace#35]
想问一下有转onnx的代码吗？
感谢~

**Comment by mk-minchul** [comment]
I translated the question and if the question is 
"Would like to ask if there is a code to transfer onnx? thanks~"
Then the answer is no at this point! But I think the modules are comprised of vanilla torch.nn modules so it will cause no problem if you follow the steps suggested by the official documentation.

**Comment by xingjunhong** [comment]
I see you have the code to convert caffe right?

**Comment by xingjunhong** [comment]
> I translated the question and if the question is "Would like to ask if there is a code to transfer onnx? thanks~" Then the answer is no at this point! But I think the modules are comprised of vanilla torch.nn modules so it will cause no problem if you follow the steps suggested by the official documentation.


Can you provide the code to transfer to onnx?thanks
