### ISSUE TITLE
When reproducting the paper, result on IJB-B, IJB-C,Tinyface are lower than reported

### ISSUE THREAD

**Issue by yyyujintang** [mk-minchul/AdaFace#39]
I trained the model on MS1MV2, on high-quality datasets, and I got a similar result. Average 97.18(reported 97.19)
But when testing on IJB-B, IJB-C, and Tinyface, the results are lower.

<!DOCTYPE html>

Dataset | Avg on high quality | IJB-B | IJB-C | Tinyface-Rank1 | Tinyface-Rank5
-- | -- | -- | -- | -- | --
Reported in the paper | 97.19 | 95.67 | 96.89 | 68.21 | 71.54
Reproducted | 97.18 | 95.37 | 96.62 | 67.03 | 70.52

I followed the code provided and trained on 8-GPUs. And I wonder if there are some special tricks when evaluating on mixed and low-quality datasets?

And I found in the paper, Table3, (b), AdaFace trained on MS1MV2 has a better result on TinyFace than the model trained on MS1MV3. This is quite strange, MS1MV3 dataset is larger than MS1MV2, and the result should be better, but it shows a reverse result on TinyFace. Table 3 shows the trend, the model trained on MS1MV3 has better performance than the model trained on MS1MV2, but only in TinyFace, it's different. 

I wonder if it's a small mistake that the result on TinyFace is reversed on MS1MV3 and MS1MV2 ?

Hope to get your reply.

**Comment by mk-minchul** [comment]
Hi yyyujintang
The code released should work as it is without modification. 
This is the setting I used for ms1mv2. I used 2 A100 GPUs. Hope this helps. 

```
python main.py \
    --data_root /mnt/home/kimminc2/data \
    --train_data_path faces_emore \
    --val_data_path ms1m_val/faces_emore \
    --prefix ir101_ms1mv2_adaface \
    --gpus 2 \
    --use_16bit \
    --arch ir_101 \
    --batch_size 512 \
    --num_workers 16 \
    --epochs 26 \
    --lr_milestones 12,20,24 \
    --lr 0.1 \
    --head adaface \
    --m 0.4 \
    --h 0.333 \
    --low_res_augmentation_prob 0.2 \
    --crop_augmentation_prob 0.2 \
    --photometric_augmentation_prob 0.2
```
