### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [mk-minchul/AdaFace#4]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.

https://github.com/PINTO0309/PINTO_model_zoo

**Comment by mk-minchul** [comment]
Hi Pinto0309, thanks for the interest in our work. The license file has been added and it is MIT license.

**Comment by PINTO0309** [comment]
Thank you!
