### ISSUE TITLE
How do I normalize vector to 1? 

### ISSUE THREAD

**Issue by martinenkoEduard** [mk-minchul/AdaFace#54]
array_1d_norm_unit = v / np.linalg.norm(v, ord=1)
print(array_1d_norm_unit)
print(sum(array_1d_norm_unit))

gives different result.
I suppose it is because there are negative values in vectors.

**Comment by mk-minchul** [comment]
Hi martinenkoEduard
The ord is ord=2 for euclidean norm.

**Comment by martinenkoEduard** [comment]
> ord=2

Thanks!
