### ISSUE TITLE
How can I convert AdaFace similarity to percentage? 

### ISSUE THREAD

**Issue by martinenkoEduard** [mk-minchul/AdaFace#55]
How can I convert AdaFace similarity to percentage?

**Comment by mk-minchul** [comment]
We do not convert the cosine similarity to percentage as we are interested in the distance between two representations.
It is technically possible to scale range -1 to 1 of cosine similarity to 0-100. But it does not mean that it will have the same interpretation as the likelihood of two person being the same subject.
