### ISSUE TITLE
Loading Webface during training process.

### ISSUE THREAD

**Issue by khahn0213** [mk-minchul/AdaFace#58]
Hello. I'm now training adaface models (ir50 and ir101) using Webface Dataset (4M, 12M, 42M).
During training process, I've found that the structure of sub-dirs in Webface Dataset is not proper for directly using Pytorch's ImageFolder class.
So I've made csv file which contain 'person_id_num' and 'image path', but I cannot train the model with webface 42M because of OOM error.

Would you give me some advice for loading such huge dataset for effiently setting-up batchsize during training process?

**Comment by mk-minchul** [comment]
Hi khahn0213
One thing you could do is avoid loading the whole dataset. I would suggest using the technique used in https://github.com/deepinsight/insightface, that is using mxrecord file format for storing and reading the data. It is analogous to TFRecord file in tensorflow. One would need to bundle the dataset into the train.rec format as provided in InsightFace. Some useful discussion is in https://github.com/deepinsight/insightface/issues/1503.

After that, you can use the training procedure in this repository that uses the train.rec file. https://github.com/mk-minchul/AdaFace/blob/master/README_TRAIN.md

**Comment by khahn0213** [comment]
Thanks for your kind and helpful answer!
Hope you and I both do well in our respective places.

+ Do you still use your snu email? I have one or two questions about FR research :-)

**Comment by xxiMiaxx** [comment]
> Hi khahn0213 One thing you could do is avoid loading the whole dataset. I would suggest using the technique used in https://github.com/deepinsight/insightface, that is using mxrecord file format for storing and reading the data. It is analogous to TFRecord file in tensorflow. One would need to bundle the dataset into the train.rec format as provided in InsightFace. Some useful discussion is in [deepinsight/insightface#1503](https://github.com/deepinsight/insightface/issues/1503).
> 
> After that, you can use the training procedure in this repository that uses the train.rec file. https://github.com/mk-minchul/AdaFace/blob/master/README_TRAIN.md

Hi @mk-minchul, 

I did exactly what you mentioned here, but i still got an out of memory error when training adaface on webface42m, i used train.rec , and 8 * A100 GPUS with 40 GB each. i'm not sure did  I miss something ? did this happen with you?

**Comment by Gagan2002** [comment]
@khahn0213 were you able to train adaface models (ir50 and ir101) using Webface Dataset 42M ?

**Comment by khahn0213** [comment]
@Gagan2002 Yes, I changed GPU.

**Comment by khahn0213** [comment]
@Gagan2002 I use four NVIDIA RTX A6000 D6 48GB.

For stable training, batch_size is as shown below. 
`batch_size=600`
`total_batch_size= 600 *4=2400`
