### ISSUE TITLE
Custom Dataset based training image channel color 

### ISSUE THREAD

**Issue by ErolCitak** [mk-minchul/AdaFace#82]
Hi,

I am confused about the image channel color when doing custom dataset-based training and I really would like to clarify that point. As you have stated in <README_TRAIN.md> document, we are able to check our training samples folder, which is <RUN_DIR>/training_samples, to understand whether our image channel order is correct or not.

When I check the image saved in that folder, it looks like an RGB order because if I read that image with cv2 module and do not convert it from BGR to RGB, since cv2 reads images in BGR order, the result with "matplotlib.pylot" imshow shows my image is BGR order. At the same time, If I read that image with PIL module and then plot it with the same "matlotlib.pylot" imshow shows it's an RGB order.

So, should we assume that If the image in the <RUN_DIR>/training_samples folder is an RGB order, then that image color channel is correct, isn't it?

Thanks

**Comment by mk-minchul** [comment]
Thank you for the question. 
Easiest way to think about it is we use cv2.imread() to load images during evaluation. 
So this means that the loaded numpy is assumed to be BGR channel order. 
When you prepare the CustomImageFolderDataset, you have the option of `swap_color_channel`. Using this, just make sure that the `sample` is in BGR channel order. The easiest way to check it is by saving the sample by 
cv2.imwrite(path, np.asarray(sample)) and make sure that the saved image file looks okay. 
Does that clarify your question?

**Comment by ErolCitak** [comment]
It's completely clear right now. Thanks for your explanation.
