### ISSUE TITLE
uncertain_dist method that is used in "validation_lq/PFE/ijbs.py" is not implemented in the utils.py.

### ISSUE THREAD

**Issue by vipul5123** [mk-minchul/AdaFace#86]
uncertain_dist method that is used in "validation_lq/PFE/ijbs.py" is not implemented in the utils.py.

![image](https://user-images.githubusercontent.com/95170764/223087410-8c6df629-5fe6-43b4-ae2c-c192c8f5b1d2.png)

**Comment by mk-minchul** [comment]
The above function uncertain() is not needed in training AdaFace, so you can just delete it.
