### ISSUE TITLE
Tinyface Alignment

### ISSUE THREAD

**Issue by ErolCitak** [mk-minchul/AdaFace#92]
Hi,

I'm curious to learn about the Alignment Policy for the Tinyface dataset. As you have stated in [Validation_lq](https://github.com/mk-minchul/AdaFace/tree/master/validation_lq) page, it's possible to use pre-aligned images or MTCNN based alignment process can be applied.

But I realized that, when I use the MTCNN detector which is provided by yourself, can not detect faces in some images. Then I decided to decrease the detection threshold then I achieved to find those faces and got their alignment results. But in that case, my alignment result does not seem like yours.

At that point, I thought what is your alignment policy? Did you use a pre-defined threshold or min_face_size etc.? Or, you may use the thresholds which are provided in your repo, but if the face does not detected, then you may prefer to create a black canvas with 112x112 size and then copy the original image into that canvas without alignment or anything else.

I'm working on low quality face images and their enhancement procedure, In this domain Adaface is valuable paper so this is why Adaface is so important for my future research work.

Thanks

**Comment by mk-minchul** [comment]
Hi Erol 
Depending on the MTCNN implemenation and preprocessing steps, the result could vary. 
To align the tinyface images I have performed
1. squarify the image and resized to 32x32
```
square_img = squarify(image)
if square_img.shape[0] != 32:
    square_img = cv2.resize(square_img, (32,32))
```
2. And zero padded the image with int(0.1*32).
```
padding=((pad_side, pad_side), (pad_side,pad_side), (0,0))
square_img = np.pad(square_img, padding,mode='constant',constant_values=0)
```
3. If this does not produce a alignment result, I pad the image's top by int(0.3 *32) side ratio and resize it to 112x112. (Rational is that the tinyface images generally seem to have faces positioned slightly toward the top and MTCNN could handle images better if the input is not too small). 
```
high_padding=((pad_side, 0), (0,0), (0,0))
bgr = np.pad(bgr, high_padding,mode='constant',constant_values=0)
bgr = squarify(bgr)
bgr = cv2.resize(bgr, (112,112)
```

Some helpful functions.

```
def squarify(M,val=0):
    (a, b, c)=M.shape
    if a==b:
        return M
    if a>b:
        diff = a-b
        left_diff = diff // 2
        right_diff = diff - left_diff
        padding=((0,0), (left_diff,right_diff), (0,0))
    else:
        diff = b-a
        top_diff = diff // 2
        btm_diff = diff - top_diff
        padding=((top_diff, btm_diff), (0,0), (0,0))
    return np.pad(M,padding,mode='constant',constant_values=val)
```

**Comment by ErolCitak** [comment]
This to detailed and helpful. I'll follow your instructions quickly. 

Thanks for your time
